### PR TITLE
Something cool I saw

### PR DESCRIPTION
**Pull request by Blueturbo47**
:) (Quickmerge?)

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/3048

## Changelog
🆑 MCterra10, Optimumtact, BeloneX
add: Added Tail entwinement.
/🆑

### CODE REVIEW

**Comment by TeomanTheGreat** [comment]
Bruh

**Comment by park66665** [comment]
Nice

**Comment by ro5490** [comment]
I'm dissatisfied in you, but we can put it to a vote

**Comment by yorii** [comment]
vote passed

**Pull request merged**
