### PR TITLE
Memorial

### PR DESCRIPTION
**Pull request by katebishop49**
## About The Pull Request
adds a new memorial sprite for overdrive. code not yet done

## Why It's Good For The Game

soldiers shall be remembered

## Changelog
:cl:
add: adds a new sprite
/:cl:

### CODE REVIEW

**Comment by katebishop49** [comment]
@Overdrive659 @ro5490 @Kryyto 
review it, ill merge it in  5 hours or less

**Comment by katebishop49** [comment]
im retarded

**Comment by BettonnCZ** [comment]
your thing doesnt just add a sprite, you add tons of stuff
obrazek

**Comment by BettonnCZ** [comment]
either fix or edit it in your changelog

**Comment by ro5490** [comment]
> your thing doesnt just add a sprite, you add tons of stuff
> obrazek

This.
Closing til you fix this

**Pull request closed without merging**
