### PR TITLE
Adds the High Frequency Blade(From hippie station)

### PR DESCRIPTION
**Pull request by xDyouGamer**
## About The Pull Request
Adds the high frequency blade which instantly delimbs people but in turn does 0 dmg to everything else

## Why It's Good For The Game
Because its epic

## Changelog
:cl:
add: High Frequency Blade

/:cl:

### CODE REVIEW

**Comment by xDyouGamer** [comment]
I poo poo kakaed it lolll

**Comment by Kryyto** [comment]
He'll do another pr

**Comment by xDyouGamer** [comment]
Hey can you wait up i started fixing the code on my pc i only have like 1 or 2 errors left im gonna finish it when i wake up.

**Comment by Kryyto** [comment]
Sure, no problems

**Comment by xDyouGamer** [comment]
Making new pr gonna close this

**Pull request closed without merging**
