### PR TITLE
station v station held together with shitcode and flextape

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
what it says

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
usage guide:
- set map to facing worlds
- set gamemode to extended
- play

**Comment by MACIEKBAKI** [comment]
majority of the 5.7k lines of code is getting oasis to compile

**Comment by ro5490** [comment]
aaaaaaaaaaaaaaaaaa

**Review by Kryyto — APPROVED** [review]
Seems all good, it's a config change so @ro5490 will be needed to merge it.

**Comment by Kryyto** [comment]
AHH, I was reviewing, I didn't it was made, nice then

**Pull request merged**
