### PR TITLE
Removes Facingworlds from voting, and increases min pop.

### PR DESCRIPTION
**Pull request by Moccha-Bee**
## About The Pull Request
Tittle says it all

## Changelog
:cl:
removed: facing worlds from voting.
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
has oasis ever gotten 40 pop

**Comment by Kryyto** [comment]
> has oasis ever gotten 40 pop

Well yeah, but I think the minpop is too high though.

**Comment by Moccha-Bee** [comment]
> has oasis ever gotten 40 pop

This high miminimum pop, is to either make it run when there is actual pop on the server, or allow admins to force it for events, since leaving it to be voted on with pop below 10 is a bit a joke

**Comment by ro5490** [comment]
Already removed it from voting server-side
Will increase the pop at some point, 25 might be better than 40 though

**Comment by ro5490** [comment]
merged, can change again if needed tbh

**Pull request merged**
