### PR TITLE
[MIRROR] [PORT] Replaces travis with github-actions

### PR DESCRIPTION
**Pull request by Poly-The-Parrot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2902
--------------------

## About The Pull Request

ports
tgstation/tgstation#54668
tgstation/tgstation#54833
tgstation/tgstation#54780
tgstation/tgstation#54805
tgstation/tgstation#53669
tgstation/tgstation#52529

## Why It's Good For The Game

Github-actions is faster and more consistent

### CODE REVIEW

**Comment by Crossedfall** [comment]
I've corrected the mirroring issues, but, you'll be unable to merge this until the linting errors are resolved.

https://github.com/Oasis-SS13/Oasis-SS13/tree/master/icons/obj/MOVED%20TO%20OASIS%20-%20Factorycargo seems to create some duplicates (Spaces in the folder name also isn't great). Since this looks to just be a copy of another folder, it'd be best to just remove this.

https://github.com/Oasis-SS13/Oasis-SS13/blob/master/Oasis/icons/obj/Factorycargo/components/Guns_parts.dmi has irregularly named icons 
image

https://github.com/Oasis-SS13/Oasis-SS13/blob/master/Oasis/icons/obj/Factorycargo/components/medicine_parts.dmi is a corrupted/empty file and can't be parsed. (It's listed as 0KB file, added in https://github.com/Oasis-SS13/Oasis-SS13/commit/1e2545da68182e2096131c89e66657a910618f49)

**Comment by Kryyto** [comment]
> I've corrected the mirroring issues, but, you'll be unable to merge this until the linting errors are resolved.
> 
> https://github.com/Oasis-SS13/Oasis-SS13/tree/master/icons/obj/MOVED%20TO%20OASIS%20-%20Factorycargo seems to create some duplicates (Spaces in the folder name also isn't great). Since this looks to just be a copy of another folder, it'd be best to just remove this.
> 
> https://github.com/Oasis-SS13/Oasis-SS13/blob/master/Oasis/icons/obj/Factorycargo/components/Guns_parts.dmi has irregularly named icons
> image
> 
> https://github.com/Oasis-SS13/Oasis-SS13/blob/master/Oasis/icons/obj/Factorycargo/components/medicine_parts.dmi is a corrupted/empty file and can't be parsed. (It's listed as 0KB file, added in [1e2545d](https://github.com/Oasis-SS13/Oasis-SS13/commit/1e2545da68182e2096131c89e66657a910618f49))

Hey Crossed, I think I have a copy of this folder in another file, so I'll just delete the "MOVED TO OASIS Factory" or something.

**Comment by Crossedfall** [comment]
> Hey Crossed, I think I have a copy of this folder in another file, so I'll just delete the "MOVED TO OASIS Factory" or something.

Sounds good. That wont resolve the other two issues, though. Since I believe those files also exist outside of the duplicate directory.

**Comment by Kryyto** [comment]
> 
> 
> > Hey Crossed, I think I have a copy of this folder in another file, so I'll just delete the "MOVED TO OASIS Factory" or something.
> 
> Sounds good. That wont resolve the other two issues, though. Since I believe those files also exist outside of the duplicate directory.

Indeed, so I have delete all the badly named icons, and I also deleted medecine.dmi (since it's just an useless file).
But, the error apparently persist with the run_lintes, I am maybe dumb.

**Comment by Crossedfall** [comment]
> > Sounds good. That wont resolve the other two issues, though. Since I believe those files also exist outside of the duplicate directory.
> 
> Indeed, so I have delete all the badly named icons, and I also deleted medecine.dmi (since it's just an useless file).
> But, the error apparently persist with the run_linters, I am maybe dumb.
> Edit: I have forgot to rerun all the test, might be cause by this.

All good! Just needed a quick rebase.

**Pull request merged**
