### PR TITLE
[MIRROR] Tgui stat panel

### PR DESCRIPTION
**Pull request by PolyTheParrot-PR**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2771
--------------------

**Fix chat HARDER ports:**
 - https://github.com/tgstation/tgstation/pull/54030/files
 - https://github.com/tgstation/tgstation/pull/54517

## Important
client.verbs +=, client.verbs -= and client.verbs |= is now not allowed and will not function properly. Once this is merged, all PRs will be required to do client.add_verb()

## About The Pull Request

Adds in the beautiful TGUI stat panel.
Actually includes all of the verbs.

Completely depreciates statclick and /datum/verbs

## Why It's Good For The Game

It looks good.
MC no longer lags the server.

**NOTE: TABS WERE NOT SORTED ALPHABETICALLY IN THESE SCREENSHOTS (Added that afterwards)** (actually I haven't fixed that yet even 1 day later)  <-- I have now

Status:
image
image
image
image
(Not lagging the game or the server, and updating in real time)
image
image
image
image

## Todo:
 - [x] Make it so you can resize the stat panel.
 - [x] Clean up some ungodly stat code.
 - [x] Fix the single ticket manager issue

## Important things to note / Potential Issues:
This completely removes the stat panel, so if TG chat fails to load the only way to use the fix-chat verb (which barely ever fixes chat) is to type in the command line. I'll port something that adds a message to chat from TG to help with this, but for now we have a message instead.

## Changelog
:cl:
add: TGUI stat panel
del: Old stat panel
del: Depreciates /datum/verbs
del: Depreciates statclick
refactor: Refactored how verbs are added to things
refactor: Refactors stat code
fix: Ports fix fix chat from TG station
/:cl:

### CODE REVIEW

**Comment by ro5490** [comment]
OH GOD NO
NOT THIS CURSED SHIT

**Comment by ro5490** [comment]
Will merge this tomorrow bc its it's a good performance boost but yeah, it's cursed af

**Comment by Kryyto** [comment]
What do you mean "it's cursed" ? I honestly find it as fine as the previous one.

**Comment by ro5490** [comment]
I honestly hate the look and feel oof

**Pull request merged**
