### PR TITLE
[MIRROR] Bluespace Miner Config

### PR DESCRIPTION
**Pull request by PolyTheParrot-PR**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3421
--------------------
LRP can have their crutch if they really want it.

This at the very least removes the problem from MRP, who should have more than enough cooperation and players to not require the help.

## About The Pull Request
Creates the config entries:

`roundstart_bluespace_miners` , amount of boards in the RD's locker at roundstart
`bsminer_researchable`, if the currently existing node is available for research.

## Changelog
:cl:
config: Bluespace miner is now affected by config. Golden has two miners and cannot research more. Sage has no miners and cannot research more.
/:cl:

[issue link stripped]

### CODE REVIEW

**Comment by Kryyto** [comment]
Config update so I'll late Dapper merge and handle it

**Comment by ro5490** [comment]
Did this pass vote? @Kryyto

**Comment by ro5490** [comment]
Voted Out // Might merge at a later date

**Comment by ro5490** [comment]
Voted out, but Merging and disabling it via config

**Pull request merged**
